# Generated by Django 4.0.4 on 2022-05-23 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_usege_status_product_usage_status_and_more'),
        ('posts', '0003_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='assigned_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
