# Generated by Django 4.0.4 on 2022-05-23 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Sports', 'Sports'), ('Pets', 'Pets'), ('Jewelry', 'Jewelry')], max_length=150, null=True)),
                ('usege_status', models.CharField(choices=[('brand_new', 'Brand New'), ('almost_new', 'Almost New'), ('gently_new', 'Gently New'), ('havely_new', 'Havely New')], max_length=150, null=True)),
                ('post_p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
