# Generated by Django 4.0.4 on 2022-05-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_status',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Almost New', 'Almost New'), ('Gently New', 'Gently New'), ('Havely New', 'Havely New')], max_length=150, null=True),
        ),
    ]
